# Automatically bump Homebrew formula after each release
# https://github.com/mislav/bump-homebrew-formula-action
name: Homebrew
# Controls when the action will run. Triggers the workflow when new tags are pushed
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'DITA-OT version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "homebrew"
  homebrew:
    name: Bump Homebrew formula
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create pull-request
        uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.event.inputs.version, '-')" # skip prereleases
        with:
          formula-name: dita-ot
          tag-name: ${{ github.event.inputs.version }}
          base-branch: master
          download-url: https://github.com/dita-ot/dita-ot/releases/download/${{ github.event.inputs.version }}/dita-ot-${{ github.event.inputs.version }}.zip
          commit-message: |
            {{formulaName}} {{version}}
            
            Created via GitHub Action
        env:
          # Access token added as secret to repo settings
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_COMMITTER_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
