name: Debug release

on:
  workflow_dispatch

jobs:
  # Build distribution package and upload the GitHub releases
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH }}
          repository: dita-ot/docs
          event-type: release
          client-payload: '{"dita-ot-version": "${{ env.tag }}", "docs-tag": "${{ env.tag }}"}'